### ISSUE TITLE
USER STORY: Data collection

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-five#1]
As a **Data Analyst**, I want to **collect data** so that I can **analyse the data and provide insights to the stakeholders**. 

## Acceptance Criteria:

* The data should contain images which show healthy cherry leaves and cherry leaves that have powdery mildew.

   **Note**: The dataset for this project is sourced from [Kaggle](https://www.kaggle.com/codeinstitute/cherry-leaves).

## Tasks:

- [ ] generate authentication token and set permissions for the Kaggle authentication JSON
- [ ] install Kaggle package
- [ ] download Kaggle dataset
