### ISSUE TITLE
USER STORY: Build a machine learning model

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-five#11]
As a **Client**, I want **to build a machine learning model and generate reports**, so that **I can benefit from efficient and reliable verification if a tree is healthy or has powdery mildew**.

## Acceptance Criteria:

* The required degree of accuracy on the test set should be at least 97%.
* It should be possible to generate reports in csv format.

## Tasks:

- [x] Image augmentation
- [x] Create ML model
- [x] Train ML model
- [x] Evaluate model performance on test data
- [x] Predict on new file
