### ISSUE TITLE
USER STORY: Average and variability of images per label

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-five#3]
As a **Client**, I want to **display the "mean" and "standard deviation" images for cherry leaves that are healthy and cherry leaves that contain powdery mildew** so that **I can visually differentiate cherry leaves**.

## Acceptance Criteria:

* Visual representation of average cherry leaves that are healthy and cherry leaves that contain powdery mildew.
* Visual representation of image variability for cherry leaves that are healthy and cherry leaves that contain powdery mildew.

## Tasks:
- [x] Determine the average image size
- [x] Determine the mean and the standard deviation images per label (healthy / powdery mildew)
- [x] Plot and save average and variability of images per label for use in dashboard
