### ISSUE TITLE
USER STORY: Interactive and Responsive dashboard

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-five#6]
As a **Client**, I want **an interactive dashboard**, so that **I can access all the features I need from any location and use it on any device**.

## Acceptance Criteria:

* The information on the dashboard should be revealed gradually to avoid overloading the User with too much information at once.
* The dashboard should be responsive on all devices.

## Tasks:
- [x] Create multipage Streamlit dashboard with empty pages.
- [x] Build "Quick Project Summary" page
- [x] Build "Cherry Leaf Visualiser" page
- [x] Build "Mildew Detection" page
- [x] Build "Project Hypothesis" page
- [x] Build "ML Performance Metrics" page
- [x] Test the responsiveness of each page on the dashboard.
